apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: jwatsonpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jwatsonpipelinesjavascriptdocker 
    spec:
      containers:
        - name: jwatsonpipelinesjavascriptdocker 
          image: mycontainerregistrywatson0405.azurecr.io/jwatsonpipelinesjavascriptdocker
          ports:
          - containerPort: 8080